config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :friendships, only: :index

  resources :chats, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  # mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, class_name: :'User'

  has_many :notifications, foreign_key: :recipient_id

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end

  def find_friend_request(user_id)
    FriendRequest.find_by(friend_id: user_id, user_id: id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def sender?(conversation)
    self == conversation.sender
  end

  def recipient?(conversation)
    self == conversation.recipient
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]

  def index
    @users = User.all.where.not(id: current_user.id)
    ActionCable.server.broadcast "notifications#{current_user.id}", message: "hello"
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<li data-user=<%= user.id %>>
  <%= user.full_name %>
  <% if current_user.is_following?(user.id) %>
    <%= link_to "Unfollow", unfollow_user_path(user.id), method: :post, remote: true %>
  <% else %>
    <%= link_to "Follow", follow_user_path(user.id), method: :post, remote: true %>
  <% end %>
  |
  <% if request = current_user.find_friend_request(user.id) %>
    <%= link_to "Cancel Friend Request", friend_request_path(request, user_id: user.id), method: :delete, remote: true %>
  <% else %>
    <%= link_to "Send Friend Request", friend_requests_path(friend_id: user.id), method: :post, remote: true %>
  <% end %>
  |
  <% if current_user %>
    <%= link_to "Chat", chats_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
  <% end %>
</li>

app/views/users/follow.js.erb
function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.replaceWith(userHTML);
}

renderUser('<%= j render @user %>');

app/views/users/index.html.erb
<h4>Hi, <%= current_user.full_name %></h4>

<h1>Users:</h1>
<ul>
  <%= render @users %>
</ul>

<%= link_to "Friend Requests", friend_requests_path %>
|
<%= link_to "My Chats", chats_path %>